1' Makes my code more conscise and easier to edit dont have to rewrite the same code over and over'
2'when the function is called'
3 'def'
4'function is the program written and a function call is running the function'
5'as amany as you want'
6'it gest destroyed'
7'return value is a value that is saved from a function , no'
8'None'
9.'using the global keyword'
10'None'
11'checks if your pets named are all deric'
12'spam.bacon()'
13.'try and except'
14.'try is the expresiion you are testing the except you put the error you might get and to skip it'
